language: go

go:
  - "1.14"

os:
  - linux

git:
  depth: 1
  quiet: true
  submodules: false

notifications:
  email: true

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
    - BRANCH="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"

stages:
  - name: Tests

jobs:
  include:
    - stage: "Tests"
      name: "Makefile"
      install: go mod download
      script:
        - make lint
        - make test
      if: (type = push) AND (type = pull_request)